# Network Configuration
network:
  # The port that Dokploy will listen on internally
  port: 3000
  
  # Traefik port configuration
  traefik:
    # HTTP port
    port: 80
    # HTTPS port
    ssl_port: 443
  
  # The IP address that Traefik will bind to
  # Options:
  # - Specific IP (e.g., "192.168.1.100") - Uses host networking
  # - "0.0.0.0" or empty - Uses overlay network for all interfaces
  advertise_addr: "0.0.0.0"

# Docker Configuration
docker:
  # The release tag for the Dokploy service
  release_tag: "latest"
  
  # Version of Traefik to use
  traefik_version: "v3.1.2"
  
  # Version of PostgreSQL to use
  postgres_version: "16"
  
  # Version of Redis to use
  redis_version: "7"

# Database Configuration
database:
  # External database URL (leave empty to use internal database)
  url: ""
  
  # Internal database configuration
  internal:
    # Database user
    user: "dokploy"
    # Database name
    name: "dokploy"
    # Database password (change this in production!)
    password: "your_secure_password"

# Redis Configuration
redis:
  # External Redis host (leave empty to use internal Redis)
  host: ""

# File Paths
paths:
  traefik:
    config: "/etc/dokploy/traefik/traefik.yml"
    dynamic: "/etc/dokploy/traefik/dynamic"
    docker_sock: "/var/run/docker.sock"
    docker_config: "/root/.docker"

# Container Names
containers:
  traefik: "dokploy-traefik"
  postgres: "dokploy-postgres"
  redis: "dokploy-redis"
  main: "dokploy"

# Network Names
networks:
  overlay: "dokploy-network"

# Volume Names
volumes:
  postgres: "dokploy-postgres-database"
  redis: "redis-data-volume"
  docker_config: "dokploy-docker-config" 